# Site settings

title: Aleksandar Todorović
email: aleksandar.todorovic@mail.ru

description: "Student, haker i promoter open source softvera koji voli da dijeli svoje priče sa svijetom."
url: "http://bs.r3bl.me" # the base hostname & protocol for your site

twitter_username:     r3bl_
github_username:      aleksandar-todorovic
linkedin_username:    aleksandartodorovic
google_plus_username: AleksandarTodorovićr3bl
facebook_username:    aleksandar.todorovic.r3bl

# Build settings
markdown: kramdown

permalink: /:categories/:title/

gems:
  - jekyll-sitemap
